name: Build for Linux
on: [ push, pull_request ]
jobs:
  build_linux:
    name: CI for Linux
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies for Linux
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y -qq autopoint automake autoconf intltool libc6-dev libglib2.0-bin libglib2.0-dev perl wget zip bzip2 make libtool pkg-config fakeroot clang openssh-client rsync
    - name: Checkout for Linux
      uses: actions/checkout@v1
    - name: Get DeaDBeeF headers
      run: |
        echo "downloading deadbeef headers..."
        wget -q http://sourceforge.net/projects/deadbeef/files/staticdeps/ddb-headers-latest.tar.bz2/download -O ddb-headers-latest.tar.bz2
        echo "unpacking deadbeef headers..."
        mkdir include
        tar jxf ddb-headers-latest.tar.bz2 -C include
    - name: Build for Linux
      run: |
        export CFLAGS="-I include"
        autoreconf --install
        ./configure
        make
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mpris-linux-x86_64
        path: .libs/mpris.so
